remote_theme             : "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
title                    : "Digi-Rays"
title_separator          : "-"
subtitle                 : "IT consultancy services"
name                     : &name "Digi-Rays"
description              : &description "IT consultancy services"
url                      : https://www.digi-rays.com
baseurl                  : ""  # Assuming root domain
repository               : "Digi-Rays/website"
logo                     : "/img/logo-2x.svg"
masthead_title           : " "  # Hide title in masthead
timezone                 : America/Los_Angeles

# Social
twitter:
  username: jekyllrb
og_image: "/img/logo-2x.svg"

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-50755011-1"
    anonymize_ip: true

google_site_verification: "onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY"

# Custom Variables
cloudinary_url: "https://res.cloudinary.com/jekyll/image/upload/f_auto,q_auto,w_404"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/
  tutorials:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: news_item
  - scope:
      path: _tutorials
      type: tutorials
    values:
      layout: tutorials
  - scope:
      path: ""
    values:
      image: "/img/logo-2x.svg"

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Feed Config
feed:
  categories:
    - release

# Markdown Processing
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Front Matter
strict_front_matter: true

# Exclude
exclude:
  - icomoon-selection.json
  - readme.md
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
future: true
